Add CI (#14)
* Add CI config and refactor scripts to include an unattended setup

* Fix github actions trigger condition

* Fix chezmoi installation

* Fix chezmoi init command

* Fix email prompt on CI

* Fix typo

* Fix template common references

* Fix env var

* fix ci command

* fix ci script

* fix env var declaration

* fix templates

* fix unbound variable error

* fix unbound variable error

* make some improvements to the passwordless sudo logic and add cache to github actions

* refactor passwordless sudo script to make it a bit more clear

* Check if asdf dir exists

* Fix typo

* Add quiet flag to commands to reduce output noise

* Reduce more output noise

* Reduce noise from starship installation

* Fix asdf installation

diff --git a/home/.chezmoiscripts/run_once_after_02-asdf-install.sh.tmpl b/home/.chezmoiscripts/run_once_after_02-asdf-install.sh.tmpl
--- a/home/.chezmoiscripts/run_once_after_02-asdf-install.sh.tmpl
+++ b/home/.chezmoiscripts/run_once_after_02-asdf-install.sh.tmpl
@@ -1,14 +1,18 @@
-{{ template "common" }}
+{{ template "common" . -}}
 
 install_asdf() {
   bot "Checking asdf..."
   echo
   if ! _exists asdf ; then
-    read -rp "Would you like to install asdf? [y/N]" -n 1 -r -s answer
-    echo
-    if [[ $answer =~ ^[Yy]$ ]] ;then
-      action "Cloning git repo..."
-      git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.0 && source ~/.asdf/asdf.sh || { echo "Failed to clone asdf repository"; exit 1; }
+    answer=$(prompt "Would you like to install asdf?")
+    if [[ $answer =~ ^[Yy]$ ]]; then
+      if [[ ! -d ~/.asdf ]]; then
+        action "Cloning git repo..."
+        git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.0 || { echo "Failed to clone asdf repository"; exit 1; }
+      else
+        ok "asdf dir already exists, skipping cloning"
+        source ~/.asdf/asdf.sh
+      fi
     else
       ok "Skipping"
     fi
@@ -29,8 +33,7 @@ configure_asdf() {
 
 install_asdf_tools() {
   echo
-  read -rp "Would you like to install the languages defined in .tool-versions? [y/N]" -n 1 -r -s answer
-  echo
+  answer=$(prompt "Would you like to install the languages defined in .tool-versions?")
   if [[ $answer =~ ^[Yy]$ ]];then
     if cat ~/.tool-versions > /dev/null 2>&1 ;then
       while read -r line; do
diff --git a/home/.chezmoiscripts/run_once_after_09-font-fira-code-setup.sh.tmpl b/home/.chezmoiscripts/run_once_after_09-font-fira-code-setup.sh.tmpl
--- a/home/.chezmoiscripts/run_once_after_09-font-fira-code-setup.sh.tmpl
+++ b/home/.chezmoiscripts/run_once_after_09-font-fira-code-setup.sh.tmpl
@@ -1,25 +1,29 @@
-{{ if eq .chezmoi.os "linux" -}}
+{{- if eq .chezmoi.os "linux" -}}
 
-{{ template "common" }}
+{{ template "common" . }}
 
 bot "Fira Code setup."
-read -p "Would you like to install Fira Code NerdFont to get cool icons on the terminal? [y/N]" -n 1 -r -s answer
-echo
-if [[ $answer =~ ^[Yy]$ ]] ;then
-  action "Downloading from https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraCode.zip"
-  wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraCode.zip
-  if [ -f "FiraCode.zip" ]; then
-    action "Unzipping and adding to ~/.fonts..."
-    unzip FiraCode.zip -d ~/.fonts
-    fc-cache -fv
-    action "rm -rf FiraCode.zip"
-    rm -rf FiraCode.zip
+
+if ! fc-list | grep -qi "Fira Code" > /dev/null 2>&1; then
+  answer=$(prompt "Would you like to install Fira Code NerdFont to get cool icons on the terminal?")
+  if [[ $answer =~ ^[Yy]$ ]]; then
+    action "Downloading from https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraCode.zip"
+    wget -q https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraCode.zip && \
+    if [ -f "FiraCode.zip" ]; then
+      action "Unzipping and adding to ~/.fonts..."
+      unzip -q FiraCode.zip -d ~/.fonts && \
+      fc-cache -f > /dev/null
+      action "Cleaning up..."
+      rm -f FiraCode.zip
+    else
+      error "Download failed. FiraCode.zip not found."
+      exit 1
+    fi
   else
-    error "Download failed. FiraCode.zip not found."
-    exit 1
+    ok "Skipping"
   fi
 else
-  ok "Skipping"
+  ok "Fira Code already installed!"
 fi
 
-{{ end -}}
+{{- end -}}
