Add CI config and refactor scripts to include an unattended setup

diff --git a/home/.chezmoiscripts/run_once_after_09-font-fira-code-setup.sh.tmpl b/home/.chezmoiscripts/run_once_after_09-font-fira-code-setup.sh.tmpl
--- a/home/.chezmoiscripts/run_once_after_09-font-fira-code-setup.sh.tmpl
+++ b/home/.chezmoiscripts/run_once_after_09-font-fira-code-setup.sh.tmpl
@@ -3,23 +3,28 @@
 {{ template "common" }}
 
 bot "Fira Code setup."
-read -p "Would you like to install Fira Code NerdFont to get cool icons on the terminal? [y/N]" -n 1 -r -s answer
-echo
-if [[ $answer =~ ^[Yy]$ ]] ;then
-  action "Downloading from https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraCode.zip"
-  wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraCode.zip
-  if [ -f "FiraCode.zip" ]; then
-    action "Unzipping and adding to ~/.fonts..."
-    unzip FiraCode.zip -d ~/.fonts
-    fc-cache -fv
-    action "rm -rf FiraCode.zip"
-    rm -rf FiraCode.zip
+
+if ! fc-list | grep "Fira code" > /dev/null 2>&1; then
+  answer=$(prompt "Would you like to install Fira Code NerdFont to get cool icons on the terminal?")
+  echo
+  if [[ $answer =~ ^[Yy]$ ]]; then
+    action "Downloading from https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraCode.zip"
+    wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraCode.zip
+    if [ -f "FiraCode.zip" ]; then
+      action "Unzipping and adding to ~/.fonts..."
+      unzip FiraCode.zip -d ~/.fonts
+      fc-cache -fv
+      action "rm -rf FiraCode.zip"
+      rm -rf FiraCode.zip
+    else
+      error "Download failed. FiraCode.zip not found."
+      exit 1
+    fi
   else
-    error "Download failed. FiraCode.zip not found."
-    exit 1
+    ok "Skipping"
   fi
 else
-  ok "Skipping"
+  ok "Fira Code already installed!"
 fi
 
 {{ end -}}
